// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgofDhKLEuA3cGwhcUjOMb_Qxuhwxn3O4',
    appId: '1:641634699819:web:d40486cdb4bdce243ff86e',
    messagingSenderId: '641634699819',
    projectId: 'fir-push-notification-6cec0',
    authDomain: 'fir-push-notification-6cec0.firebaseapp.com',
    storageBucket: 'fir-push-notification-6cec0.appspot.com',
    measurementId: 'G-RF1HVBVZLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1QTh9jaFTFTeAq6xcF_mZkknDKEatSI8',
    appId: '1:641634699819:android:bccb05ababf5972e3ff86e',
    messagingSenderId: '641634699819',
    projectId: 'fir-push-notification-6cec0',
    storageBucket: 'fir-push-notification-6cec0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ_7aMnlSS100nAetgxJxJYwBjLRJMcJM',
    appId: '1:641634699819:ios:db87229c7267e36a3ff86e',
    messagingSenderId: '641634699819',
    projectId: 'fir-push-notification-6cec0',
    storageBucket: 'fir-push-notification-6cec0.appspot.com',
    iosClientId: '641634699819-b1n6seb1iv7s9vcjkkihugsm6f3cl7sr.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ_7aMnlSS100nAetgxJxJYwBjLRJMcJM',
    appId: '1:641634699819:ios:a73f931962eca63a3ff86e',
    messagingSenderId: '641634699819',
    projectId: 'fir-push-notification-6cec0',
    storageBucket: 'fir-push-notification-6cec0.appspot.com',
    iosClientId: '641634699819-7clljcjv2osvm1ael9q5fe0d5codrq1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp.RunnerTests',
  );
}
